services:
  app:
    image: nginx:1.21.3
    ports:
      - "8080:80"
      - "443:443"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
