version: "3.9"

services:
  app:
    container_name: nginx
    image: nginx:1.21.3
    build:
      dockerfile: ./dockerfile
    ports:
      - "8080:80"
      - "443:443"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
