name: Install Nginx
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install nginx
      - run: sudi systemctl start nginx
    